version: "3"
services:
  gql:
    ports:
      - "127.0.0.1:8080:8080"
    build: .
    command: go run server.go
    volumes:
      - ./:/go/src
  db:
    image: mysql:latest
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=smart_shopping
